#!/bin/sh -e

cpus=4
mem="768M"
if [ -e /dev/kvm ]; then
echo Trying to use KVM...
kvm="--enable-kvm -cpu host"
else
kvm="--accel tcg,thread=multi"
fi

fallocate -l 11g logdev.ext4 && mkfs.ext4 -O ^has_journal,^uninit_bg,^ext_attr,^huge_file,^64bit -q logdev.ext4
sync
qemu-system-x86_64 -nographic -serial mon:stdio -m $mem -smp $cpus $kvm -kernel "$1" \
	-drive file="$2",index=0,readonly=on,media=cdrom \
	-drive file=logdev.ext4,if=virtio,index=1,media=disk \
	-drive file="$3",if=virtio,index=2,media=disk \
	-drive file="$4",if=virtio,index=3,media=disk \
	-drive file="$5",if=virtio,index=4,media=disk \
	-net nic,model=e1000 -net user \
	-append "net.ifnames=0 root=/dev/sr0 console=ttyS0 qemuktest.timeout=$6 qemuktest.seed=$7"

(mkdir -p mnt && sudo mount -o loop logdev.ext4 mnt && find mnt -maxdepth 1 -type f -exec cp '{}' . \; && sudo umount mnt)
rm -f logdev.ext4
{ [ -f exitstatus ] && [ "x`cat exitstatus`" = "x0" ]; }
